# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('contact_type', models.CharField(choices=[('C', 'Company'), ('I', 'Individual')], max_length=1, verbose_name='contact type')),
                ('born_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='born in')),
                ('extra_emails', models.ManyToManyField(blank=True, related_name='_contact_extra_emails_+', related_query_name='+', to='persons.ExtraEmailAddress', verbose_name='extra email addresses')),
                ('phone_numbers', models.ManyToManyField(blank=True, related_name='_contact_phone_numbers_+', related_query_name='+', to='persons.PhoneNumber', verbose_name='phone numbers')),
                ('physical_addresses', models.ManyToManyField(blank=True, related_name='_contact_physical_addresses_+', related_query_name='+', to='persons.PhysicalAddress', verbose_name='physical addresses')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
