# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, default='', help_text='Documento Nacional de Identidad means National Identity Document. Everyone in Argentina has one. ', max_length=10, unique=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, default='', help_text="Clave Única de Identificación Tributaria means Unique Code of Tributary Identification. Everybody who isn't an employee under somebody's payroll has one.", max_length=14, unique=True, verbose_name='CUIT')),
                ('cuil', models.CharField(blank=True, default='', help_text="Clave Única de Identificación Laboral means Unique Code of Labor Identification. Everybody who is an employee under somebody's payroll has one.", max_length=14, unique=True, verbose_name='CUIL')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.Client')),
            ],
            options={
                'verbose_name': 'client',
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='CompanyInvoiceAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, default='', help_text="Clave Única de Identificación Tributaria means Unique Code of Tributary Identification. Everybody who isn't an employee under somebody's payroll has one. Even companies, NGOs, Fundations, etc.", max_length=14, unique=True, verbose_name='CUIT')),
                ('iibb', models.CharField(blank=True, default='', help_text="Ingresos Brutos means Brute Income. It is a unique code given by fiscal regulators of provinces' ", max_length=15, verbose_name='IIBB')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.CompanyInvoice')),
            ],
            options={
                'verbose_name': 'company',
                'default_permissions': ('view', 'add', 'change', 'delete'),
                'verbose_name_plural': 'companies',
            },
        ),
    ]
