# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinvoice',
            name='fiscal_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='persons.PhysicalAddress', verbose_name='fiscal address'),
        ),
        migrations.AlterField(
            model_name='contactinvoice',
            name='fiscal_position',
            field=models.ForeignKey(help_text='Certain countries require a fiscal position for its taxpayers.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', related_query_name='contact', to='invoice.FiscalPosition', verbose_name='fiscal position'),
        ),
    ]
